<?php
?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <title>Affiligate Widget</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <?php include_once("lib/analytics.phtml")?>
    <script type="text/javascript">
        window.onload = function() {

            // Listing to postMessage to initiate a preview action
            window.addEventListener("message", refreshWidget, false);
        };
        // Upon postMessage - widget redirects itself to the server to preview the changed settings
        function refreshWidget(event) {
            var compId = getParameterByName("compId");
            if ( event.data.secret === "AffiliGate" ) {
                if (compId === event.data.compId) {
                    var query_sting = 'asin=' + event.data.asin;
                    query_sting += '&layoutName=' + event.data.layoutName;
                    query_sting += '&layoutSettings=' + JSON.stringify(event.data.layoutSettings);
                    window.location = 'widget.php?' + query_sting;
                }
            }
        }

        function getParameterByName(name) {
            name = name.replace(/[\[]/, "\\\[").replace(/[\]]/, "\\\]");
            var regexS = "[\\?&]" + name + "=([^&#]*)";
            var regex = new RegExp(regexS);
            var results = regex.exec(window.location.search);
            if(results === null) {
                return "";
            }
            else {
                return decodeURIComponent(results[1].replace(/\+/g, " "));
            }
        }
    </script>
</head>
<body>
    <?php include_once("renderers/".$layoutName.".phtml") ?>
</body>
</html>