<?php
?>

<!DOCTYPE>
<html>
<head>
	<title>Affiligate</title>
	
	<link rel="stylesheet" type="text/css" href="assets/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="assets/css/bootstrap-responsive.min.css">
	<link rel="stylesheet" type="text/css" href="assets/css/custom.css">
	
	<script type="text/javascript">
        var aff = {};
        aff.widgetData = <?php echo json_encode($widgetData);?>;
        aff.userData = <?php echo json_encode($userData);?>;

	</script>
	<script src="assets/js/jquery-1.8.0.min.js" type="text/javascript"></script>	
	<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="assets/js/handlebars-1.0.0.beta.6.js" type="text/javascript"></script>	
	<script src="assets/js/custom.js" type="text/javascript"></script>
	
	<script id="product-list-template" type="text/x-handlebars-template">
  		{{#each payLoad}}
  			<li>
  				<img src="{{this.images.small.url}}" height="{{this.images.small.width}}" width="{{this.images.small.height}}"/>
  				<div class="text-data">
  					<p class="title">{{this.title}}</p>
  					<p class="price">{{this.price}}</p>
  				</div>
  				<button class="btn btn-primary">Select</button>
  				<div class="cb">&nbsp;</div>
  			</li>
  		{{/each}}
	</script>

	
</head>
<body>
	<div id="container">
		<div id="main">
			<div class="alert">&nbsp;</div>
			<section id="header" class="section">
				<div id="logo40">&nbsp;</div>
				<div id="main-title">
					<h3>Affiligate</h3>
					<nav>
						<a id="return-to-search" href="#">New Search</a>
						<a id="settings" href="#">Settings</a>
						<a id="return-to-home" href="#">Home</a>		
					</nav>

					<p>Start by searching for the products you'd like to display on your page. Customize your banner's layout and text. To connect to your affiliate program, click Settings and enter your Affiliate ID in the area provided.</p>
				</div>
				<div id="user-settings">
					<input id="settings-amazon-affiliate-id" type="text" class="pull-left" placeholder="Your Amazon Affiliate ID" />
					<button id="user-settings-submit" type="submit" class="btn pull-left">Update</button>
				</div>	
				<div class="cb">&nbsp;</div>
			</section>
			<section class="section" id="search-section">
				<div id="search-section-wrapper">
					<h4>Search Product</h4>
					<form id="search-query-form">
						<input id="search-query" type="text" class="pull-left" placeholder="Search Product or ASIN">
			
						<div class="btn-group pull-left clearfix">
						  <button id="product-select-disabled" class="btn btn-large" value="All">All Departments</button>
						  <button class="btn btn-large dropdown-toggle" data-toggle="dropdown">
						    <span class="caret"></span>
						  </button>
						  <ul class="dropdown-menu" id="search-query-list">
						  	<li><a href="#" value="All">All Departments</a></li>
							<li class="divider">&nbsp;</li>
							<li><a href="#" value="Blended">Blended</a></li>
							<li><a href="#" value="Apparel">Apparel</a></li>
							<li><a href="#" value="Automotive">Automotive</a></li>
							<li><a href="#" value="Baby">Baby</a></li>
							<li><a href="#" value="Beauty">Beauty</a></li>
							<li><a href="#" value="Books">Books</a></li>
							<li><a href="#" value="Classical">Classical</a></li>
							<li><a href="#" value="DigitalMusic">Digital Music</a></li>
							<li><a href="#" value="DVD">DVD</a></li>
							<li><a href="#" value="Electronics">Electronics</a></li>
							<li><a href="#" value="ForeignBooks">Foreign Books</a></li>
							<li><a href="#" value="GourmetFood">Gourmet Food</a></li>
							<li><a href="#" value="Grocery">Grocery</a></li>
							<li><a href="#" value="HealthPersonalCare">Health Personal Care</a></li>
							<li><a href="#" value="Hobbies">Hobbies</a></li>
							<li><a href="#" value="HomeGarden">Home Garden</a></li>
							<li><a href="#" value="HomeImprovement">Home Improvement</a></li>
							<li><a href="#" value="Industrial">Industrial</a></li>
							<li><a href="#" value="Jewelry">Jewelry</a></li>
							<li><a href="#" value="KindleStore">Kindle Store</a></li>
							<li><a href="#" value="Kitchen">Kitchen</a></li>
							<li><a href="#" value="Magazines">Magazines</a></li>
							<li><a href="#" value="Merchants">Merchants</a></li>
							<li><a href="#" value="Miscellaneous">Miscellaneous</a></li>
							<li><a href="#" value="MP3Downloads">MP3s</a></li>
							<li><a href="#" value="Music">Music</a></li>
							<li><a href="#" value="MusicalInstruments">Musical Instruments</a></li>
							<li><a href="#" value="MusicTracks">Music Tracks</a></li>
							<li><a href="#" value="OfficeProducts">Office Products</a></li>
							<li><a href="#" value="OutdoorLiving">Outdoor Living</a></li>
							<li><a href="#" value="PCHardware">PC Hardware</a></li>
							<li><a href="#" value="PetSupplies">Pet Supplies</a></li>
							<li><a href="#" value="Photo">Photo</a></li>
							<li><a href="#" value="Shoes">Shoes</a></li>
							<li><a href="#" value="SilverMerchant">Silver Merchant</a></li>
							<li><a href="#" value="Software">Software</a></li>
							<li><a href="#" value="SoftwareVideoGames">Video Games</a></li>
							<li><a href="#" value="SportingGoods">Sporting Goods</a></li>
							<li><a href="#" value="Tools">Tools</a></li>
							<li><a href="#" value="Toys">Toys</a></li>
							<li><a href="#" value="VHS">VHS</a></li>
							<li><a href="#" value="Video">Video</a></li>
							<li><a href="#" value="VideoGames">Video Games</a></li>
							<li><a href="#" value="Watches">Watches</a></li>
							<li><a href="#" value="Wireless">Wireless</a></li>
							<li><a href="#" value="WirelessAccessories">Wireless Accessories</a></li>
						  </ul>
						</div>
								
						<button id="product-search-submit" type="submit" class="btn btn-primary btn-large pull-right">Search</button>
					</form>
					<div id="search-product-error-message">Search field can not be blank</div>
					<div class="cb">&nbsp;</div>
				</div>
			</section>
			
			<section class="section" id="search-result-section">
				<div class="ajax-loader-wrapper">
					<div class="ajax-loader">&nbsp</div>
				</div>
				<div id="product-list">
					<div id="waiting-for-user">
						<div id="waiting-for-user-arrow">&nbsp;</div>
						<div id="waiting-for-user-text">We are waiting for your search</div>
					</div>
					<div id="no-products">
						<div id="no-product-image">&nbsp;</div>
						<div id="no-product-text">Unfortunatly there are no results. Please try new search.</div>
					</div>
					<div id="server-error">
						Something went wrong. Please try again later.
					</div>
					<ul id="list">
						
					</ul>
				</div>
			</section>
			<section class="section" id="product-settings-secion">
				<header>
					<h3>Customize Banner</h3>
					<button id="update-product-attributes">Update</button>
					<div class="cb">&nbsp;</div>						
				</header>			
				<h4>Change skin</h4>
				<div id="skin-type">
					<a href ="#" id="Full1">
						<span class="img">&nbsp;</span>
						<span class="text">Image and text</span>
					</a>
					<a href ="#" id="Image">
						<span class="img">&nbsp;</span>
						<span class="text">Image only</span>
					</a>
					<a href ="#" id="Link">
						<span class="img">&nbsp;</span>
						<span class="text">Text only</span>
					</a>
					<div class="cb">&nbsp;</div>						
				</div>
				<h4 class="image-size-class">Change image size</h4>
				<div id="image-size" class="image-size-class">
		
		              		                    <ul class="nav">
		                      <li><a href="#" id="Small">Small</a></li>
		                      <li><a href="#" id="Medium">Medium</a></li>
		                      <li><a href="#" id="Large">Large</a></li>		                      
		                    </ul> 

		            <div class="cb">&nbsp;</div>						
				</div>
				<div class="cb">&nbsp;</div>
				<div class="line-break-skin">
					<div class="small-arrow-skin">&nbsp;</div>
				</div>
				<h4 class="product-text-class">Change title</h4>
				<textarea cols="20" id="product-text" class="product-text-class" name="product-text" placeholder="Please write your product's text..." rows="3"></textarea>
				<div class="cb">&nbsp;</div>
			</section>
		</div>
	</div>
</body>
</html>