<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style type="text/css">
        body {
            font-family: verdana, sans-serif;
            font-size: 12px;
        }
        a:visited {
            color: #0000FF;
        }
        .column {
            display: inline-block;
            float: left;
        }
        .column.right {
            width: 40%;
            margin-left: 12px;
            vertical-align: top;
        }
        p {
            margin: 0;
        }
        .right p.price {
            font-weight: bold;
            margin-bottom: 18px;
        }
        .right p.title {
            margin-bottom: 9px;
            line-height: 17px;
        }
    </style>
</head>
<body>
<div class="column left">
    <a href="<?php echo $product["url"];?>" target="<?php echo $content["linkTarget"];?>">
        <img src="<?php echo $product["images"][$content["size"]]["url"]; ?>", width="<?php echo $product["images"][$content["size"]]["width"]; ?>",height="<?php echo $product["images"][$content["size"]]["height"]; ?>" />
		</a>
	</div>
	<div class="column right">
		<p class="title">
			<a href="<?php echo $product["url"];?>" target="_<?php echo $content["linkTarget"];?>"><?php echo $product["title"];?></a>
		</p>
		<p class="price"><?php echo $product["price"];?></p>
		<a href="<?php echo $product["url"];?>" target="<?php echo $content["linkTarget"];?>"><img src="assets/img/amazon_buy_1.gif" /></a>
	</div>

</body>
</html>