<?php
/**
 * Created by JetBrains PhpStorm.
 * User: RoyK
 * Date: 8/29/12
 * Time: 7:42 PM
 */
?>
<a target="<?php echo $content["linkTarget"];?>" href="http://www.amazon.com/gp/product/<?php echo $row["amazon_asin"];?>/ref=as_li_tf_il?ie=UTF8&camp=1789&creative=9325&creativeASIN=<?php echo $row["amazon_asin"];?>&linkCode=as2&tag=<?php echo $associateTag;?>"><img border="0" src="http://ws.assoc-amazon.com/widgets/q?_encoding=UTF8&ASIN=<?php echo $row["amazon_asin"];?>&Format=<?php echo $content["size"];?>&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=<?php echo $associateTag;?>" ></a><img src="http://www.assoc-amazon.com/e/ir?t=<?php echo $associateTag;?>&l=as2&o=1&a=<?php echo $row["amazon_asin"];?>" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />