<?php
/**
 * Created by JetBrains PhpStorm.
 * User: RoyK
 * Date: 8/29/12
 * Time: 7:42 PM
 */
?>
<a href="<?php echo $product["url"];?>" target="<?php echo $content["linkTarget"];?>">
    <img src="<?php echo $product["images"][$content["size"]]["url"]; ?>", width="<?php echo $product["images"][$content["size"]]["width"]; ?>",height="<?php echo $product["images"][$content["size"]]["height"]; ?>", border="0" />
</a>