<?php
?>

<a target="<?php echo $content["linkTarget"];?>" href="http://www.amazon.com/gp/product/<?php echo $asin;?>/ref=as_li_tf_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=<?php echo $asin;?>&linkCode=as2&tag=<?php echo $associateTag;?>"><?php echo $content["title"];?></a><img src="http://www.assoc-amazon.com/e/ir?t=<?php echo $associateTag;?>&l=as2&o=1&a=<?php echo $asin;?>" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important; color: #2361A1;" />